version: '3.8'
services:
  db:
    image: postgres:15
    container_name: javamail-db
    environment:
      POSTGRES_DB: javamail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: